In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'i am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7482, 5198, 6126, 7258],
 [7482, 5198, 6126, 9017],
 [7482, 3903, 6126, 1332],
 [7224, 4623, 5633, 5134, 4142],
 [7224, 4623, 5633, 5134, 9427],
 [113, 7482, 761, 6126, 7983],
 [7254, 9116, 6227, 5134]]

In [6]:
# word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [7]:
import numpy as np

In [8]:
# the sentences are not of the same length, hence we add 0's either before or after the sentence to make them of the same length using pad sequence.
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7482 5198 6126 7258]
 [   0    0    0    0 7482 5198 6126 9017]
 [   0    0    0    0 7482 3903 6126 1332]
 [   0    0    0 7224 4623 5633 5134 4142]
 [   0    0    0 7224 4623 5633 5134 9427]
 [   0    0    0  113 7482  761 6126 7983]
 [   0    0    0    0 7254 9116 6227 5134]]


In [9]:
# feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,output_dim=dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\yuvra\OneDrive\Desktop\Self Projects\SELF\IMDB simple RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)